using System;
using System.Collections.Generic;
using System.Text;
using System.Collections.ObjectModel;

namespace Dataaccess
{
    class mylist
    {
        public ObservableCollection<listmovies> list { get; set; }
        public mylist()
        {
            list = new ObservableCollection<listmovies>();
            list.Add(new listmovies { name = "Ám ảnh kinh hoàng (The Conjuring)", time = "2015", image = "https://upload.wikimedia.org/wikipedia/vi/b/b9/Conjuring_2.jpg",noidung= "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Trốn thoát (Get Out)", time = "2013", image = "https://i1.wp.com/vuviphimzz.com/wp-content/uploads/2017/03/Get-Out-Get-Out-2017-3-650x325.png" , noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Chú hề ma quái (IT)", time = "2017", image = "https://www.elleman.vn/wp-content/uploads/2019/09/11/review-phim-IT-chapter-2-elle-man-1.jpg" , noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "The Shining", time = "1980", image = "https://revelogue.com/wp-content/uploads/2019/11/phim-the-shining.jpg" , noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Annabelle", time = "2014", image = "https://cdn.baogiaothong.vn/files/f1/2014/09/30/su-that-lanh-nguoi-ve-nhung-bup-be-bi-quy-am.jpg", noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Hereditary (Dòng máu bị nguyền rủa)", time = "2018", image = "https://bimbim.tv/storage/2020/10/lHV8HHlhwNup2VbpiACtlKzaGIQ-185x278.jpg", noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Gã hề ma quái 2 (IT 2)", time = "2019", image = "https://ss-images.catscdn.vn/2019/07/16/5626299/ngang.jpg", noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Quỷ ám (The Exorcist)", time = "1973", image = "https://isach.info/images/story/cover/quy_am__william_peter_blatty.jpg" , noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Vùng đất câm lặng (A quiet place)", time = "2018", image = "https://assets-vtvcab.gviet.vn/images/hq/posters/vung-dat-cam-lang-vungdatcamlang-2019041957.jpg", noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
            list.Add(new listmovies { name = "Vòng tròn định mệnh (The ring)", time = "2002", image = "https://upload.wikimedia.org/wikipedia/vi/4/4e/The_ring_poster2.jpg", noidung = "Ám ảnh kinh hoàng là series phim kinh dị siêu nhiên rất nổi tiếng của Mỹ, phim được lần đầu công chiếu vào năm 2013. Trong phim,hai nhân vật chính Ed và Lorraine Warren là cặp vợ chồng điều tra các hiện tượng siêu nhiên xảy ra trên nước Mỹ.Những báo cáo của họ còn truyền cảm hứng cho cuốn tiểu thuyết Amityville Horror.Hai vợ chồng Warren đã đến để hỗ trợ gia đình Perron(Ron Livingston và Lili Taylor) đang trải qua các sự kiện ngày càng đáng lo ngại trong trang trại của họ ở Harrisville,Rhode Island." });
        }
    }
}
